In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [2]:
#assigning the URL with variable name url
url = 'https://www.imdb.com/search/title/?count=100&groups=top_1000&sort=user_rating'
#request allow you to send HTTP request
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

In [3]:
movie_name = []
year = []
time = []
rating = []
metascore = []
votes = []
gross = []

In [4]:
movie_data = soup.findAll('div', attrs ={'class': 'lister-item mode-advanced'})

In [5]:
for store in movie_data:
    name = store.h3.a.text
    movie_name.append(name)
    
    year_of_release = store.h3.find('span', class_ = 'lister-item-year text-muted unbold').text.replace('(', '').replace(')', '')
    year.append(year_of_release)
    
    runtime = store.p.find('span', class_ = 'runtime').text.replace(' min', '')
    time.append(runtime)
    
    rate = store.find('div', class_ = 'inline-block ratings-imdb-rating').text.replace('\n', '')
    rating.append(rate)
    
    meta  = store.find('span', class_ = 'metascore').text.replace(' ', '') if store.find('span', class_ = 'metascore') else '^^^^^^'
    metascore.append(meta)
    
    value = store.find_all('span', attrs = {'name': 'nv'})
    
    vote = value[0].text
    votes.append(vote)
    
    grosses = value[1].text if len(value) >1 else '*****'
    gross.append(grosses)

In [6]:
movie_DF = pd.DataFrame({'Name of movie': movie_name, 'Year of relase': year, 'Watchtime': time, 'Movie Rating': rating, 'Metascore': metascore, 'Votes': votes, 'Gross collection': gross})

In [7]:
movie_DF

,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection
0,Nhà tù Shawshank,1994,142,9.3,82,"2,808,822",$28.34M
1,Bố Già,1972,175,9.2,100,"1,957,385",$134.97M
2,Kỵ Sĩ Bóng Đêm,2008,152,9.0,84,"2,790,512",$534.86M
3,Bản Danh Sách Của Schindler,1993,195,9.0,95,"1,411,993",$96.90M
4,Chúa Tể Của Những Chiếc Nhẫn: Sự Quay Trở Lại ...,2003,201,9.0,94,"1,922,775",$377.85M
...,...,...,...,...,...,...,...
95,Nguyện Cầu Cho Một Giấc Mơ,2000,102,8.3,71,"877,526",$3.64M
96,Ông Trùm Mặt Sẹo,1983,170,8.3,65,"888,093",$45.60M
97,Chàng Will Tốt Bụng,1997,126,8.3,70,"1,026,320",$138.43M
98,Cỗ Máy Tội Phạm,1971,136,8.3,77,"862,192",$6.21M
99,Tia Nắng Vĩnh Cửu Của Tâm Hồn Tinh Khiết,2004,108,8.3,89,"1,049,347",$34.40M

In [8]:
movie_DF.to_excel("Top_100_IMDB_Movies.xlsx")

In [9]:
movie_DF.head(7)

,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection
0,Nhà tù Shawshank,1994,142,9.3,82,"2,808,822",$28.34M
1,Bố Già,1972,175,9.2,100,"1,957,385",$134.97M
2,Kỵ Sĩ Bóng Đêm,2008,152,9.0,84,"2,790,512",$534.86M
3,Bản Danh Sách Của Schindler,1993,195,9.0,95,"1,411,993",$96.90M
4,Chúa Tể Của Những Chiếc Nhẫn: Sự Quay Trở Lại ...,2003,201,9.0,94,"1,922,775",$377.85M
5,12 Người Đàn Ông Giận Dữ,1957,96,9.0,97,"836,120",$4.36M
6,Bố Già Phần II,1974,202,9.0,90,"1,329,137",$57.30M